apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deno-webserver.fullname" . }}
  labels:
    {{- include "deno-webserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.webserver.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "deno-webserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deno-webserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "deno-webserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      initContainers:
        - name: {{ .Chart.Name }}-init
          image: busybox:1.31
          command: [ 'sh', '-c', 'echo -e "Checking for the availability of MariaDB Server deployment"; while ! nc -z maria-db 3306; do sleep 1; printf "-"; done; echo -e "  >> MariaDB Server has started";' ]

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /probe?probeType=startup
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            httpGet:
              path: /probe?probeType=liveness
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 600
            httpGet:
              path: /probe?probeType=readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.webserver.volumeMounts }}
          volumeMounts:
          {{- range $volume := .Values.webserver.volumeMounts }}
              -   name: {{ $volume.name }}
                  mountPath: {{ $volume.mountPath }}
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
      {{- range $volume := .Values.webserver.volumes }}
          -   name: {{ $volume.name }}
              persistentVolumeClaim:
                  claimName: {{ $volume.claimName }}
      {{- end }}
      {{- end }}
