{{- if .Values.volumes }}
{{- range $volume := .Values.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ $volume.name }}
spec:
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: {{ $volume.persistentVolumeReclaimPolicy | default "retain" }}
    storageClassName: {{ $volume.storageClassName | default "standard" }}
    capacity:
        storage: {{ $volume.size }}
    hostPath:
        path: {{ $volume.path }}

{{- end }}
{{- end }}
---
{{- if .Values.volumeClaims }}
{{- range $volumeClaim := .Values.volumeClaims }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ $volumeClaim.name }}
    namespace: {{ $volumeClaim.namespace | default "default" }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ $volumeClaim.size }}

{{- end }}
{{- end }}
